/*
 * Order Lunch Ginno
 *
 * This is a order lunch server for everyone worked at Ginnovation. APIs are writed by swagger [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * API version: 1.0.0
 * Contact: apiteam@ginno.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"database/sql"
)

// User user in Ginno
type User struct {
	ID int64 `json:"id,omitempty"`

	Username string `json:"username,omitempty"`

	Email string `json:"email,omitempty"`

	Password string `json:"password,omitempty"`

	// User Status
	UserStatus string `json:"userStatus,omitempty"`
}

func (u *User) createUser(db *sql.DB) error {
	err := db.QueryRow(
		"INSERT INTO users(username, email, password, userstatus) VALUES($1, $2, $3, $4) RETURNING id",
		u.Username, u.Email, u.Password, u.UserStatus).Scan(&u.ID)
	if err != nil {
		return err
	}
	return nil
}

func (u *User) getLoginInfo(db *sql.DB) error {
	err := db.QueryRow("SELECT * FROM users WHERE id=$1",
		u.ID).Scan(&u.ID, &u.Username, &u.Password, &u.UserStatus, &u.Email)
	return err
}
