/*
 * Order Lunch Ginno
 *
 * This is a order lunch server for everyone worked at Ginnovation. APIs are writed by swagger [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * API version: 1.0.0
 * Contact: apiteam@ginno.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// Route Route
type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

// Routes Routes
type Routes []Route

// NewRouter NewRouter
func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

// Index Index
func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"CreateDish",
		strings.ToUpper("Post"),
		"/dish",
		CreateDish,
	},

	Route{
		"GetListDish",
		strings.ToUpper("Get"),
		"/dish/getList",
		GetListDish,
	},

	Route{
		"AddOrder",
		strings.ToUpper("Post"),
		"/order",
		AddOrder,
	},

	Route{
		"DeleteOrder",
		strings.ToUpper("Delete"),
		"/order/{orderId}",
		DeleteOrder,
	},

	Route{
		"GetListOrder",
		strings.ToUpper("Get"),
		"/order/getList",
		GetListOrder,
	},

	Route{
		"GetOrderById",
		strings.ToUpper("Get"),
		"/order/{orderId}",
		GetOrderByID,
	},

	Route{
		"GetTotalOrder",
		strings.ToUpper("Get"),
		"/order/getTotal",
		GetTotalOrder,
	},

	Route{
		"UpdateOrder",
		strings.ToUpper("Put"),
		"/order/{orderId}",
		UpdateOrder,
	},

	Route{
		"CreateUser",
		strings.ToUpper("Post"),
		"/user",
		CreateUser,
	},

	Route{
		"LoginUser",
		strings.ToUpper("Get"),
		"/user/login",
		LoginUser,
	},
}
